### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by zany130** [MyHCel/Maya-For-Arch#1] opened 2021-08-21 06:18 UTC
When the script opens Maya for the first time so that I can log in it immediately crashes. I can open it manually but and it will let me sign in but the app crashes with a segmentation fault after logging in.

```
maya
/usr/autodesk/maya2022/bin/maya.bin: /usr/lib/libtiff.so.5: no version information available (required by /usr/autodesk/maya2022/lib/libmayaOpenImageIO.so.2.0)
/usr/bin/maya: line 220: 1183974 Segmentation fault      (core dumped) /usr/autodesk/maya2022/bin/maya.bin
```
here is the output of the script
https://hastebin.com/werudumeda.yaml

**Comment by deedox** [comment] 2021-09-03 19:26
same issue here. running on manjaro with kernel 5.13.12-1. please help

**Comment by costashatz** [comment] 2021-09-06 15:20
@MyHCel thanks for this nice guide..

I am also getting this on arco (pure) arch linux with kernel 5.13.13-arch1-1. I also tried the "official" AUR package (there are a few minor differences with your repo) and I get the same behavior. Interestingly mayapy works fine. You can see the discussion at the AUR package: https://aur.archlinux.org/packages/maya/.

In the README it says that Maya segfaults if we login with a serial key. I did not use a serial key, but logged in with my account. Is this OK or should we use a "Network License"?

Any more ideas?

**Comment by MyHCel** [comment] 2021-09-06 18:45
Hi!
I apologise for my lack of response. I currently have a quite busy schedule.
I'll try the installation with Maya's latest release as soon as I can. Unfortunately, I don't have a dedicated testing machine. I will be testing on my main computer, which is running Arch with the kernel 5.10.61-1-lts.

As far as I know, segmentation fault errors are bounded to how the application was programmed. I could be wrong though.
I'll update you when I get the results.

**Comment by MyHCel** [comment] 2021-09-07 15:07
Quick update

I downloaded the most recent version of Maya 2022 and is not working on my system either. I have my bets on a dependency change. It could be that they may have added a new dependency or that Arch updated the OpenSSL version to 1.1.1.l-1 (it worked with 1.1.1.k).

If it is not that... welp, we'll see.

**Comment by mottosso** [comment] 2021-09-07 18:25
I'm also having this problem!

**Comment by costashatz** [comment] 2021-09-20 08:23
Hello @MyHCel ... Looks like there is already a solution available: https://aur.archlinux.org/packages/maya/. There was a problem with `libmd.so`. Creating an empty one (e.g. `touch libmd.so`) in maya's lib folder, fixes the segfault. I can verify that this is working nicely.

**Comment by MyHCel** [comment] 2021-09-21 02:59
Hi @costashatz 
Thanks for letting me know C:
I suspected that the problem was caused by a change in the Arch repos, but I had no idea of exactly what.

I just added the fix to the script.
The sign in window is still not working well on the first run (at least for me), but it does on the second one.
Now everything seems to be working again.

Thanks.

**Comment by costashatz** [comment] 2021-09-21 05:56
> The sign in window is still not working well on the first run (at least for me), but it does on the second one.

Installing things using the AUR package, the sign-in was working fine from the first time for me. No idea if it related but just in case.

**Comment by costashatz** [comment] 2021-09-21 08:10
@MyHCel btw I guess we can close this now..Thanks!

**Closed as completed** 2021-09-21 23:37 UTC

**Comment by totopo3d** [comment] 2022-03-17 18:40
Almost worked, but it crashes at start.
In the Maya.env I have dissabled several things
`MAYA_OPENCL_IGNORE_DRIVER_VERSION=1
MAYA_DISABLE_OPENCL=1
MAYA_CM_DISABLE_ERROR_POPUPS=1
MAYA_COLOR_MGT_NO_LOGGING=1
TMPDIR=/tmp`

It generates a .ma file in tmp and crashes anyway. I'm out of ideas. Here is the crash file. I don't know what to do at this point.
[Maya_20220317_1127_crash.txt](https://github.com/MyHCel/Maya-For-Arch/files/8289261/Maya_20220317_1127_crash.txt)
